# site settings
title: The Union of UK Unicyclists
shorttitle: UUU
subtitle: The Union of UK Unicyclists
email: committee@unicycle.org.uk
description: The Union of UK Unicyclists promotes the sport and art of unicycling in the UK. 
baseurl: "" # the subpath of your site, e.g. /blog
#url: www.unicycle.org.uk # the base hostname & protocol for your site
url: mchonofsky.github.io/unionofukunicyclists
country: United Kingdom

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 8

# social settings
facebook_url: https://www.facebook.com/theunionofukunicyclists/
instagram_url: # https://instagram.com/...
twitter_url: https://www.twitter.com/UUUnicyclists

# build settings
markdown: kramdown

sass:
  style: compressed
